apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.15.0
    helm:
      values: |
        pushgateway:
          enabled: false
        server:
          service:
            type: ClusterIP
            # type: LoadBalancer
            # servicePort: 9090
            # servicePort: 81
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true